language: python

# need mongo for the popit-api we launch in the background
services:
  - mongodb

# 2.6.1 is used on our servers
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"

# command to run tests
script:
  - ./start_local_popit_api.bash
  - ./manage.py test popit -v 2

# report results in IRC
notifications:
  irc: "irc.mysociety.org#popit"
  use_notice: true
  skip_join: true
