language: python

# need mongo for the popit-api we launch in the background
services:
  - mongodb

# 2.6.1 is used on our servers
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=">=1.3,<1.4"
  - DJANGO_VERSION=">=1.4,<1.5"
  - DJANGO_VERSION=">=1.5,<1.6"

# command to install dependencies
install:
  - pip install "Django$DJANGO_VERSION" --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests, and check build still sane
# Would like to run 'python setup.py check' too, but it does not work on 2.6
script:
  - ./start_local_popit_api.bash
  - python setup.py test

# report results in IRC
notifications:
  irc: "irc.mysociety.org#popit"
  use_notice: true
  skip_join: true
