language: python

# need mongo for the popit-api we launch in the background
services:
  - mongodb

# 2.6.1 is used on our servers
python:
  - "2.7"

env:
  - DJANGO_VERSION=">=1.7,<1.8"
  - DJANGO_VERSION=">=1.8,<1.9"

# command to install dependencies
install:
  - pip install "Django$DJANGO_VERSION"
  - pip install -r requirements.txt

# command to run tests, and check build still sane
# Would like to run 'python setup.py check' too, but it does not work on 2.6
script:
  - ./start_local_popit_api.bash
  - ./runtests.py

# report results in IRC
notifications:
  irc: "irc.mysociety.org#popit"
  use_notice: true
  skip_join: true
